<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage.Master" CodeBehind="WebForm1.aspx.cs" Inherits="CircularManagementSystem.WebForm1" %>

<asp:Content ID="contentHeader" runat="server" ContentPlaceHolderID="contentLogin" runtat="server">
    <div>
        <asp:GridView ID="EmployeeView" runat="server" AutoGenerateColumns="False" DataKeyNames="EmployeeId" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit"
            OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="HeaderId" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("EmployeeId") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="LabelId" runat="server" Text='<%# Bind("EmployeeId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="HeaderName" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="TxtName" runat="server" Text='<%# Bind("EmployeeName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="LabelName" runat="server" Text='<%# Bind("EmployeeName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="HeaderPhone" runat="server">
                    <EditItemTemplate>
                        <asp:TextBox ID="TxtPhone" runat="server" Text='<%# Bind("EmployeePhoneNumber") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="LabelPhone" runat="server" Text='<%# Bind("EmployeePhoneNumber") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
